[package]
name = "bitcoinkernel-covenants"
version = "0.0.22"
edition = "2021"
rust-version =  "1.71.0"
authors = ["TheCharlatan <seb.kung@gmail.com>", "stutxo <stutxo@proton.me>"]
description = "Safe Rust bindings to libbitcoinkernel with added covenant op_codes"
license = "MIT"
repository = "https://github.com/stutxo/rust-bitcoinkernel-covenants/tree/covenants_enabled"
documentation = "https://docs.rs/bitcoinkernel"
keywords = ["bitcoin", "ffi", "libbitcoinkernel"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"

[dependencies]
libbitcoinkernel-sys-covenants = { path = "libbitcoinkernel-sys-covenants", version = "0.0.21" }

[dev-dependencies]
hex = "0.4"
env_logger = "0.11"
log = "0.4"
bitcoin = "0.31"
tempdir = "0.3"
silentpayments = "0.1"
secp256k1 = "0.28"

[workspace]
members = [
    "examples",
    "fuzz",
    "libbitcoinkernel-sys-covenants"
]
